CREATE TABLE IF NOT EXISTS SimplifiedStudentProfileCaseRecords (
    RecordID INT AUTO_INCREMENT PRIMARY KEY,
    IncidentID INT NULL,
    RespondentName VARCHAR(500) NOT NULL,
    DateOfOffense DATETIME NOT NULL,
    ViolationCommitted VARCHAR(255) NOT NULL,
    ViolationCategory VARCHAR(100) NULL,
    Description TEXT NULL,
    EvidencePhotoBase64 LONGTEXT NULL,
    StudentSignatureBase64 LONGTEXT NULL,
    Status ENUM('Active', 'Resolved', 'Closed') DEFAULT 'Active',
    IsActive TINYINT(1) DEFAULT 1,
    CreatedBy INT NULL,
    DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- Parent information
    AdviserName VARCHAR(255) NULL,
    FathersName VARCHAR(100) NULL,
    MothersName VARCHAR(100) NULL,
    GuardianName VARCHAR(100) NULL,
    ParentContactType VARCHAR(50) NULL,
    ParentContactName VARCHAR(255) NULL,
    ParentMeetingDate DATETIME NULL,
    -- Case details
    ActionTaken TEXT NULL,
    Findings TEXT NULL,
    Agreement TEXT NULL,
    PenaltyAction TEXT NULL,
    DateOfBirth DATE NULL,
    Age INT NULL,
    Sex VARCHAR(20) NULL,
    Address TEXT NULL,
    GradeLevel VARCHAR(50) NULL,
    TrackStrand VARCHAR(100) NULL,
    Section VARCHAR(50) NULL,
    FOREIGN KEY (IncidentID) REFERENCES SimplifiedIncidentReports(IncidentID) ON DELETE SET NULL
);
